[package]
name = "hyprsnipe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
dotenvy = "0.15.7"
reqwest = { version = "0.12.8", features = ["blocking", "socks"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
